var output = ['Platformer',
    'Action-Adventure',
    'First-Person Shooter',
    'Sports',
    'Soccer',
    'Music/Rhythm',
    'Action',
    'Brawler',
    'Football',
    'Basketball',
    'Driving/Racing',
    'Shooter',
    'Baseball',
    'Adventure',
    'Fighting',
    'Puzzle',
    'Role-Playing',
    'Compilation',
    'Simulation',
    'Hockey',
    'Strategy',
    'Wrestling',
    'Golf'
];