var physicalGamesList = ["Angry Birds Star Wars",
    "Assassin's Creed IV: Black Flag",
    "Battlefield 4",
    "Call of Duty: Ghosts",
    "FIFA 14",
    "Just Dance 2014",
    "Injustice: Gods Among Us - Ultimate Edition",
    "Killzone: Shadow Fall",
    "Knack",
    "LEGO Marvel Super Heroes",
    "Madden NFL 25",
    "NBA 2K14",
    "NBA Live 14",
    "Need for Speed Rivals",
    "Skylanders Swap Force",
    "Putty Squad",
    "The Pinball Arcade",
    "Tomb Raider: Definitive Edition",
    "The LEGO Movie Videogame",
    "Rayman Legends",
    "Thief",
    "Metal Gear Solid V: Ground Zeroes",
    "inFamous: Second Son",
    "Dynasty Warriors 8: Complete Edition",
    "LEGO The Hobbit",
    "Final Fantasy XIV Online: A Realm Reborn",
    "Trials Fusion",
    "The Amazing Spider-Man 2",
    "MLB 14: The Show",
    "Bound by Flame",
    "Wolfenstein: The New Order",
    "Watch Dogs",
    "Murdered: Soul Suspect",
    "EA Sports UFC",
    "MotoGP 14",
    "Transformers: Rise of the Dark Spark",
    "Sniper Elite 3",
    "The Last of Us Remastered",
    "Diablo III: Ultimate Evil Edition",
    "Madden NFL 15",
    "Metro Redux",
    "Warriors Orochi 3 Ultimate",
    "Destiny",
    "NHL 15",
    "FIFA 15",
    "Middle-earth: Shadow of Mordor",
    "Natural Doctrine",
    "Sherlock Holmes: Crimes & Punishments",
    "Minecraft: PlayStation 4 Edition",
    "Alien: Isolation",
    "Driveclub",
    "NBA 2K15",
    "Sleeping Dogs: Definitive Edition",
    "The Evil Within",
    "MXGP: The Official Motocross Videogame",
    "Just Dance 2015",
    "Samurai Warriors 4",
    "SingStar: Ultimate Party",
    "Lords of the Fallen",
    "NBA Live 15",
    "Call of Duty: Advanced Warfare",
    "Rocksmith 2014 Edition",
    "The Wolf Among Us",
    "Assassin's Creed Unity",
    "LEGO Batman 3: Beyond Gotham",
    "Pro Evolution Soccer 2015",
    "Dragon Age: Inquisition",
    "Far Cry 4",
    "Grand Theft Auto V",
    "LittleBigPlanet 3",
    "WWE 2K15",
    "Akiba's Trip: Undead & Undressed",
    "The Crew",
    "Guilty Gear Xrd -SIGN-",
    "Motorcycle Club",
    "Saints Row IV: Re-Elected",
    "Rugby 15",
    "Dying Light",
    "Evolve",
    "Dragon Ball: Xenoverse",
    "Dead or Alive 5: Last Round",
    "The Order: 1886",
    "Dynasty Warriors 8 Empires",
    "DmC: Devil May Cry Definitive Edition",
    "Battlefield Hardline",
    "Bladestorm: Nightmare",
    "Final Fantasy Type-0 HD",
    "Resident Evil: Revelations 2",
    "RIDE",
    "Bloodborne",
    "MLB 15: The Show",
    "Dark Souls II: Scholar of the First Sin",
    "Mortal Kombat X",
    "Omega Quintet",
    "Project CARS",
    "Final Fantasy X / X-2 HD Remaster",
    "The Elder Scrolls Online: Tamriel Unlimited",
    "LEGO Jurassic World",
    "Payday 2: Crimewave Edition",
    "Batman: Arkham Knight",
    "BlazBlue: Chrono Phantasma Extend",
    "F1 2015",
    "Deception IV: The Nightmare Princess",
    "God of War III Remastered",
    "Godzilla",
    "Rory McIlroy PGA Tour",
    "Onechanbara Z2: Chaos",
    "Legend of Kay Anniversary",
    "Risen 3: Titan Lords - Enhanced Edition",
    "Dishonored: Definitive Edition",
    "Madden NFL 16",
    "One Piece: Pirate Warriors 3",
    "Until Dawn",
    "Metal Gear Solid V: The Phantom Pain"];

module.exports = physicalGamesList;


